name: project_2nd_june
description: ''
version: 1.0.0
author: suman.shiwam@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: project2ndjune
  parentArtefactID: sumanshiwamprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2026-06-01 20:32:42'
pipelines:
  pipelines/bronze_lh:
    name: bronze_lh
    description: bronze_layer
    author: suman.shiwam@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2026-06-01 20:32:42'
    datasets:
      inputs:
      - datasets/br_accounts
      - datasets/br_opportunities
      - datasets/br_products
      outputs:
      - datasets/bronze_accounts
      - datasets/bronze_opportunities
      - datasets/bronze_products
    subgraphs: []
    dependencies: {}
  pipelines/error_handling:
    name: error_handling
    description: ''
    author: suman.shiwam@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2026-06-01 22:02:30'
    datasets:
      inputs:
      - datasets/malformed
      outputs:
      - datasets/bronze_accounts_validated
      - datasets/bronze_corrupt_quarantine
    subgraphs: []
    dependencies: {}
  pipelines/daily_incremental_load:
    name: daily_incremental_load
    description: ''
    author: suman.shiwam@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2026-06-02 13:41:18'
    datasets:
      inputs:
      - datasets/incremental_load
      outputs:
      - datasets/bronze_daily_events
    subgraphs: []
    dependencies: {}
datasets:
  datasets/br_accounts:
    name: br_accounts
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:18:40'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:18:40'
  datasets/br_opportunities:
    name: br_opportunities
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:25:27'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:25:27'
  datasets/br_products:
    name: br_products
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:33:01'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:33:01'
  datasets/bronze_accounts:
    name: bronze_accounts
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:50:48'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:50:48'
  datasets/bronze_opportunities:
    name: bronze_opportunities
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:54:11'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:54:11'
  datasets/bronze_products:
    name: bronze_products
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 21:55:13'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 21:55:13'
  datasets/malformed_records:
    name: malformed_records
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 22:07:58'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 22:07:58'
  datasets/malformed:
    name: malformed
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-01 22:38:15'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: File
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-01 22:38:15'
  datasets/bronze_accounts_validated:
    name: bronze_accounts_validated
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-02 10:27:08'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-02 10:27:08'
  datasets/bronze_corrupt_quarantine:
    name: bronze_corrupt_quarantine
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-02 10:28:14'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-02 10:28:14'
  datasets/incremental_load:
    name: incremental_load
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-02 14:38:26'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: File
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-02 14:38:26'
  datasets/bronze_daily_events:
    name: bronze_daily_events
    description: ''
    author: suman.shiwam@prophecy.io
    createdAt: '2026-06-02 21:55:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 143
        datasetType: Database
        description: ''
        author: suman.shiwam@prophecy.io
        createdAt: '2026-06-02 21:55:20'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2026-06-01 20:32:42'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2026-06-01T20:32:42.811669Z'
  name: plibMaven
  version: 9.3.0
  id: '277481617'
  createdAt: '2026-06-01T20:32:42.811669Z'
  type: plibMaven
- modifiedAt: '2026-06-01T20:32:42.811669Z'
  name: plibPypi
  version: 2.1.17
  id: '1584480404'
  createdAt: '2026-06-01T20:32:42.811669Z'
  type: plibPypi
projectDependencies:
  '5':
    projectUID: 5
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/Hyz8gPVP_team_2/Hyz8gPVP_project_5.git&subPath=
    version: 0.0.10
    isDefault: true
    author: null
    createdAt: '2026-06-01 20:30:30'
  '4':
    projectUID: 4
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/Hyz8gPVP_team_2/Hyz8gPVP_project_4.git&subPath=
    version: 0.2.55
    isDefault: true
    author: null
    createdAt: '2026-06-01 20:30:30'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
